sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t colgandm/super-broccoli -f Dockerfile.dev .

script:
  - docker run -e CI=true colgandm/super-broccoli npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'super-broccoli'
  env: 'Superbroccoli-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-043272625120'
  bucket_path: 'super-broccoli'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY