sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t colgandm/super-broccoli -f Dockerfile.dev .

script:
  - docker run -e CI=true colgandm/super-broccoli npm run test
